server:
    port: 8089

logging:
    level:
        io.tinyrpc: debug

tinyrpc:
    consumer:
        # zookeeper server
        registryAddress: 127.0.0.1:2181
        # registry center type, zookeeper/nacos/apoll/etcd/eureka
        registryType: zookeeper
        # registry loadbalance type: zkconsistenthash
        loadBalanceType: zkconsistenthash
        # proxy type/javassist/jdk
        proxy: cglib
        # version
        version: 1.0.0
        # group
        group: hello
        # zkconsistenthash
        serializationType: zkconsistenthash
        # timeout
        timeout: 30000
        # async
        async: false
        # oneway
        oneway: false
        # heartbeatInterval
        heartbeatInterval: 30000
        # scanNotActiveChannelInterval
        scanNotActiveChannelInterval: 60000
        # retryInterval
        retryInterval: 1000
        # retryTimes
        retryTimes: 3
        # enableResultCache
        enableResultCache: false
        # resultCacheExpire
        resultCacheExpire: 5000
        # enableDirectServer
        enableDirectServer: false
        # directServerUrl
        directServerUrl:
        # corePoolSize
        corePoolSize: 3
        # maximumPoolSize
        maximumPoolSize: 5
        # flowType
        flowType: print
        # enableBuffer
        enableBuffer: false
        # bufferSize
        bufferSize: 6
        # enableBuffer
        reflectType: jdk
        # bufferSize
        fallbackClassName:
        # enableRateLimiter
        enableRateLimiter: true
        # rateLimiterType
        rateLimiterType: counter
        # permits
        permits: 10
        # milliSeconds
        milliSeconds: 1000
        # rateLimiterFailStrategy
        rateLimiterFailStrategy: exception

